apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-webhook-operator.fullname" . }}
  labels:
    {{- include "k8s-webhook-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-webhook-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-webhook-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
