apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-webhook-operator.fullname" . }}
  labels:
    {{- include "k8s-webhook-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete","get","list","watch"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get","list","watch"]
